### ISSUE TITLE
[BUG] php-fpm is not required

### ISSUE THREAD

**Issue by killbus** [linuxserver/docker-snapdrop#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the `php-fpm` is up with the container.

### Expected Behavior

drop the `php-fpm` service.

### Steps To Reproduce

1. docker-compose.yml
  ```yaml
      ---
      version: "2.1"
      services:
        snapdrop:
          image: lscr.io/linuxserver/snapdrop:latest
          container_name: snapdrop
          restart: always
          environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
```

2. `docker compose up -d`
3. `docker compose exec snapdrop ps -aux`

### CPU architecture

arm64

### Docker creation

```bash
---
      version: "2.1"
      services:
        snapdrop:
          image: lscr.io/linuxserver/snapdrop:latest
          container_name: snapdrop
          restart: always
          environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
```

### Container logs

```bash
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.1  0.0    200    64 ?        Ss   06:24   0:00 /package/admi
root          15  0.0  0.0    204    68 ?        S    06:24   0:00 s6-supervise 
root          17  0.0  0.0    192     4 ?        Ss   06:24   0:00 /package/admi
root          38  0.0  0.0    204    68 ?        S    06:24   0:00 s6-supervise 
root          39  0.0  0.0    204    68 ?        S    06:24   0:00 s6-supervise 
root          40  0.0  0.0    204    64 ?        S    06:24   0:00 s6-supervise 
root          41  0.0  0.0    204    64 ?        S    06:24   0:00 s6-supervise 
root          42  0.0  0.0    204    68 ?        S    06:24   0:00 s6-supervise 
root          43  0.0  0.0    204    68 ?        S    06:24   0:00 s6-supervise 
root          51  0.0  0.0    180    48 ?        Ss   06:24   0:00 /package/admi
abc          235  2.0  0.2 243780 49760 ?        Ssl  06:24   0:00 /usr/bin/node
root         236  0.2  0.0  33732 14796 ?        Ss   06:24   0:00 php-fpm: mast
root         239  0.0  0.0   1692   984 ?        Ss   06:24   0:00 /usr/sbin/cro
root         241  0.1  0.0  18100  6328 ?        Ss   06:24   0:00 nginx: master
abc          251  0.0  0.0  18548  2608 ?        S    06:24   0:00 nginx: worker
abc          252  0.0  0.0  18548  2608 ?        S    06:24   0:00 nginx: worker
abc          253  0.0  0.0  18548  2608 ?        S    06:24   0:00 nginx: worker
abc          254  0.0  0.0  18548  2236 ?        S    06:24   0:00 nginx: worker
abc          265  0.0  0.0  33740  3504 ?        S    06:24   0:00 php-fpm: pool
abc          266  0.0  0.0  33740  3504 ?        S    06:24   0:00 php-fpm: pool
root         277 33.3  0.0   3200  2280 pts/0    Rs+  06:24   0:00 ps -aux
```
```
